- name: Add a group for Caddy
  group:
    name: "{{ caddy_group }}"

- name: Add a user for Caddy
  user:
    name: "{{ caddy_user }}"

- name: Create Caddy directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0755
  with_items:
    - "{{ caddy_root }}"
    - "{{ caddy_conf_root }}"
    - "{{ caddy_ssl_root }}"

- name: Install Caddy web server
  unarchive:
    src: https://caddyserver.com/download/linux/amd64?plugins=tls.dns.digitalocean&license=personal&telemetry=off
    dest: "{{ caddy_root }}"
    remote_src: yes
  notify: Copy Caddy executable

- name: Copy Caddy systemd service
  template:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0644
  notify: Restart Caddy

- name: Copy Caddy configuration
  template:
    src: Caddyfile
    dest: "{{ caddy_conf_root }}/Caddyfile"
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0644
  notify: Reload Caddy
