- name: Add Docker apt signing key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: >
      deb [arch=amd64] https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable
    filename: docker
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present
  notify: Start Docker
